@Micro.Seraph.AspNetCore.Api_HostAddress = https://localhost:7208

PUT {{Micro.Seraph.AspNetCore.Api_HostAddress}}/sample/Add

###

PATCH {{Micro.Seraph.AspNetCore.Api_HostAddress}}/sample/Delete?intId=0

###

GET {{Micro.Seraph.AspNetCore.Api_HostAddress}}/sample/List

###

POST {{Micro.Seraph.AspNetCore.Api_HostAddress}}/sample/Update

###
